logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
  r2dbc:
    url: r2dbc:h2:mem:///test
    name: sa
    password:
  datasource:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

webclientexample:
  #  postsapi:
  #    host: https://localhost
  h2-console-port: 8081
