logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

spring:
  r2dbc:
    url: r2dbc:pool:mysql://root:@127.0.0.1:3306/testdb
    user: root
    password:
  pool:
    initial-size: 100
    max-size: 500
    max-idle-time: 30m
    validation-query: SELECT 1
